### ISSUE TITLE
Exception when logging in

### ISSUE THREAD

**Issue by LokiMidgard** [viswanathr88/OnePlayer#17]
I just cloned the reposetory and wanted to test this app. But I got following Exception when I try to login:
```
Login failed with status ProviderError, Error Code: 2156265475, ErrorMessage: Die Anwendung, von der Authentifizierungstokens angefordert werden, ist entweder deaktiviert oder nicht korrekt konfiguriert.
```

Roughly translated "The Application, that is requestion Authenticationtokens, is deactevited or not correct configured"

Do I need to set something up before I can test it?

**Comment by viswanathr88** [comment]
Hi, Can you please give me  some more details?
-  Android app or the windows app?
- When did you see this error? After clicking on the ‘Log in with OneDrive’ button at launch?

Thanks

**Comment by LokiMidgard** [comment]
It happens using the UWP app and clicking `Log in with OneDrive` button.

The exception is thrown in the `GetMsaTokenAsync` method in the file `WindowsLoginManager.cs` and is catched in the empty catch. block.

**Comment by viswanathr88** [comment]
This happens mostly because the app needs to be associated with the store. This creates a Package.StoreAssociation.xml file. You will need a create an app with a reserved name in your dev center and associate this app with that reserved name. In VS2019, you can do this right clicking on the project -> Publish -> Associate App with the Store. I don't know if there is a way to re-use my store entry.

Let me know if this works for you. If you do know how it can be re-used, let me know too.

**Comment by LokiMidgard** [comment]
Ah ok, that makes sense, from securety point. Actually I wanted to try it out but did not find it in the MS store, so I decided to build it from source. Can you post a link to the store entry?

**Comment by viswanathr88** [comment]
This app is not ready to release at all. It's still being actively developed. It can sync metadata and display it. It can't play music yet. So I haven't published it in the store. But still, an association is required, which I have.
If you still would like to try it, feel free to create a dummy app in your dev center and associate it with that.

**Comment by LokiMidgard** [comment]
I will look into it, If I found out how it works, I post an Update.

Thanks

**Comment by LokiMidgard** [comment]
I played a little arround and I think #3 would be a better approach then that every one that want to work with the code register it as store app.
